# Generated by Django 2.2 on 2022-01-30 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='submission date'),
            preserve_default=False,
        ),
    ]
