# Generated by Django 2.2 on 2022-02-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0004_auto_20220130_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='correct',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
