# Generated by Django 2.2 on 2022-02-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_auto_20220201_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submissions',
            new_name='Submission',
        ),
    ]
